title: 'C++ course : beginner to advanced'
description: C++ course from beginner to advanced
template:
  repo: 'c++-course-:-beginner-to-advanced-template'
  name: 'c++-course-:-beginner-to-advanced'
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
